name : First Workflow
on: [push, ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "This is first step from job 1" >> msg.txt

      - name: List Files
        run: cat msg.txt
        
