name : Multiple Job Workflow 1
on: [push, ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v4.1.6

      - name: Welcome Message
        run: echo "This is first step from job 1" > msg.txt
      
      - name: List Files
        run: |
          cat msg.txt
          ls -la
          cat README.md

      - name: Install Cowsay
        run: sudo apt-get install cowsay -y
        
      - name: Generate ASCII Artwork
        run: |
          cowsay -f dragon "Run for cover, I am a Dragon....... RAWR" > dragon.txt
          cat dragon.txt

      - name: Sleep for some time.
        run: sleep 30
  
  second_job:
            runs-on: ubuntu-latest
            steps:
              - name : checkout
                uses: actions/checkout@v4.1.6
        
              - name: Welcome Message
                run: echo "This is  second job" >> msg2.txt
              
              - name: List Files
                run: |
                  cat msg2.txt
                  ls -la
                  cat README.md
        
              - name: Install Cowsay
                run: sudo apt-get install cowsay -y
                
              - name: Generate ASCII Artwork
                run: |
                  cowsay -f turtle "Run for cover, I am a turtle...... RAWR" > dragon2.txt
                  cat dragon2.txt

              - name: Sleep for some time.
                run: sleep 20

  third_job:
                    runs-on: ubuntu-latest
                    steps:
                      - name : checkout
                        uses: actions/checkout@v4.1.6
                
                      - name: Welcome Message
                        run: echo "This is third job" > msg3.txt
                      
                      - name: List Files
                        run: |
                          cat msg3.txt
                          ls -la
                          cat README.md
                
                      - name: Install Cowsay
                        run: sudo apt-get install cowsay -y
                        
                      - name: Generate ASCII Artwork
                        run: |
                          cowsay -f bunny "Run for cover, I am a Dragon....... RAWR" > dragon3.txt
                          cat dragon3.txt